---
# Install tasks for debian

- block:
    - name: add https support to apt
      package:
        name: apt-transport-https
        state: present

    - name: add gpg keys for virtualbox repository in apt
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - https://www.virtualbox.org/download/oracle_vbox_2016.asc
        - https://www.virtualbox.org/download/oracle_vbox.asc

    - name: setup virtualbox repository
      apt_repository:
        repo: >-
            deb
            https://download.virtualbox.org/virtualbox/{{ ansible_distribution
                                                          | lower }}
            {{ ansible_distribution_release }} contrib
        state: present
        update_cache: yes
        filename: virtualbox
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::packages
    - role::virtualbox_engine::install
