---
# Install tasks

- block:
    - include_tasks: "{{ install_playbook }}"
      vars:
        install_playbook: >-
          {{ role_path }}/tasks/install/{{ ansible_os_family | lower }}.yml

    - include_tasks: "{{ role_path }}/tasks/install/common.yml"
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::packages
    - role::virtualbox_engine::install
