---
# Configuration tasks

- block:
    - name: Ensure vboxusers group is present
      group:
        name: vboxusers
        state: present
        system: yes

    - name: Add users into vboxusers group
      user:
        append: yes
        groups: vboxusers
        state: present
        name: '{{ item }}'
      loop: "{{ virtualbox_engine_users | default([]) }}"
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::configure
