---
# Role tasks

- block:
    - include_tasks: install.yml
      tags:
        - role::virtualbox_engine::install

    - include_tasks: configure.yml
      tags:
        - role::virtualbox_engine::configure
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::virtualbox_engine
