---
# Role tasks

- name: Install virtualbox engine
  include_tasks: install/main.yml
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::install

- name: Configure virtualbox engine
  include_tasks: configure/main.yml
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::configure
