---
# Role tasks

- include_tasks: install.yml
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::install

- include_tasks: configure.yml
  tags:
    - role::virtualbox_engine
    - role::virtualbox_engine::configure
